### ISSUE TITLE
add Frontier cells to UI

### ISSUE THREAD

**Issue by Raa37** [openwsn-berkeley/Atlas#182] opened 2022-05-17 11:11 UTC

**Comment by Raa37** [comment] 2022-05-17 11:17
cellsFrontier -> red cells on UI/map

**Comment by twatteyne** [comment] 2022-05-18 06:48
This is probably a duplicate of #181?

**Comment by Raa37** [comment] 2022-05-18 08:33
> 

- This issue is just for representing frontiers cells as red cells in UI, it's that starting step for #183 which is why i'm using the same branch for both and will create one pull request for the both of them together.

**Closed as completed** 2022-05-23 16:24 UTC
